# Generated by Django 4.0.4 on 2023-04-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_product_last_fetched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Price',
        ),
    ]
