# Generated by Django 4.0.4 on 2023-04-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_fetched',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
