# Generated by Django 4.0.4 on 2023-04-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_products_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Retreivals',
            field=models.IntegerField(null=True),
        ),
    ]
