# Generated by Django 4.0.4 on 2023-04-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_products_last_fetched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Retreivals',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
