# Generated by Django 4.0.4 on 2023-04-17 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_products_retreivals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Retreivals',
        ),
        migrations.RemoveField(
            model_name='products',
            name='last_fetched',
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fetched', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products')),
            ],
        ),
    ]
