# Generated by Django 4.0.4 on 2023-04-17 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_products_retreivals_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetail',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
