# Generated by Django 4.0.4 on 2023-04-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='date_fetched',
            field=models.DateTimeField(),
        ),
    ]
