# Generated by Django 4.0.4 on 2023-04-18 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_productdetail_date_fetched'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetail',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
