# Generated by Django 4.0.4 on 2023-04-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetail',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
